# Data Preprocessing

In [6]:
!git clone https://github.com/indichealth/indic-health-demo.git

Cloning into 'indic-health-demo'...
remote: Enumerating objects: 231, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 231 (delta 55), reused 103 (delta 43), pack-reused 110
Receiving objects: 100% (231/231), 1.24 MiB | 23.96 MiB/s, done.
Resolving deltas: 100% (99/99), done.


In [7]:
%cd indic-health-demo/Dataset

/content/indic-health-demo/Dataset/indic-health-demo/Dataset


In [8]:
import pandas as pd
import os

In [9]:
data_path = 'IHQID-WebMD'

In [ ]:
train_ = pd.read_csv(os.path.join(data_path, 'train.csv'))
test_ = pd.read_csv(os.path.join(data_path, 'test.csv'))

In [10]:
train_.head(20)

question_english  \
0                    what is nystatin prescribed for?   
1   can douching after sex stop me from getting pr...   
2                     does percocet cause weight gain   
3   does 2 or 2 1/2 glasses of wine a day caues hi...   
4               can too much buttermilk cause thrush?   
5   i still don't understand the procedure of gett...   
6        is it safe to take emergen-c while pregnant?   
7   how can i protect my skin from dryness this wi...   
8   is there a cream that can fix wrinkles on your...   
9   can yeast infection cause back pain in lower r...   
10         is it wrong to take antibiotics for colds?   
11          is tendonitis the same as a pulled tendon   
12  could taking valium result in a false positive...   
13  can coconut oil cure jock itch or is there som...   
14  can i have sex with a pregnant woman while tak...   
15         will a blood transfusion get rid of herpes   
16       do testosterone injections cause weight gain   
17  brownish vaginal discharge every two weeks in ...   
18  scoliosis. does it effect the stomach and brea...   
19                              what is an acne scar?   

               disease_english             drug_english  treatment_english  \
0                          NaN                 nystatin                NaN   
1                     pregnant                      NaN                NaN   
2                  weight gain                 percocet                NaN   
3          high blood pressure                      NaN                NaN   
4                       thrush                      NaN                NaN   
5                          NaN                      NaN                NaN   
6                          NaN                emergen-c                NaN   
7                      dryness                      NaN                NaN   
8            wrinkles, flaccid                      NaN                NaN   
9   yeast infection, back pain                      NaN                NaN   
10                       colds              antibiotics                NaN   
11   tendonitis, pulled tendon                      NaN                NaN   
12                         NaN                   Valium     pregnency test   
13                   jock itch              coconut oil                NaN   
14                         NaN             valasiclovir                NaN   
15                      herpes                      NaN  blood transfusion   
16                 weight gain  Testosterone Injections                NaN   
17  brownish vaginal discharge                      NaN                NaN   
18                   Scoliosis                      NaN                NaN   
19                   Acne scar                      NaN                NaN   

                                       question_hindi  \
0            निस्टेटिन किस लिए निर्धारित किया गया है?   
1   क्या सम्भोग के बाद डाउचिंग मुझे गर्भवती होने स...   
2            क्या पेर्कोसेट वजन बढ़ने का कारण बनता है   
3   क्या एक दिन में शराब के २ या २ १/२ गिलास उच्च ...   
4         क्या बहुत अधिक छाछ थ्रश का कारण बन सकती है?   
5   मैं अभी भी स्वास्थ्य बीमा प्राप्त करने की प्रक...   
6   क्या गर्भवती होने पर एमर्जेन-सी लेना सुरक्षित है?   
7   मैं इस सर्दी में अपनी त्वचा को रूखेपन से कैसे ...   
8   क्या कोई ऐसा क्रीम हैं जो लिंग के सिर पर झुर्र...   
9   क्या यीस्ट इन्फेक्शन के कारण कमर के निचले हिस्...   
10       क्या सर्दी के लिए एंटीबायोटिक्स लेना गलत है?   
11          टेंडोनाइटिस एक खींचे गए कण्डरा के समान है   
12  एक गर्भावस्था परीक्षण पर एक झूठी सकारात्मक में...   
13  क्या नारियल का तेल जॉक खुजली का इलाज कर सकता ह...   
14  क्या मैं एक गर्भवती महिला के साथ वैलासिक्लोविर...   
15           क्या खून चढ़ाने से दाद से छुटकारा मिलेगा   
16  क्या टेस्टोस्टेरोन इंजेक्शन वजन बढ़ाने का कारण...   
17  मेरी १२ साल की उम्र में हर दो हफ्ते में भूरा य...   
18  क्या स्कोलियोसिस पेट और साँस लेने को प्रभावित ...   
19                          मुँहासे का निशान क्या है?   

  

In [11]:
!pip install transformers[torch] datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 52.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 493.7/493.7 kB 45.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 37.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 105.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 90.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.4/261.4 kB 36.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 20.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 32.2 MB/s eta 0:00:00


In [12]:
from transformers import AutoTokenizer
model_id = 'roberta-base'
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [ ]:
# text = ""
# enc = tokenizer.encode(text, return_tensors="pt")
# dec = tokenizer.convert_ids_to_tokens(enc[0])
# dec

In [13]:
def biotagging(data: pd.DataFrame, lang):
  data = data.fillna('') # replace nan values with empty string
  # add column for tokens from tokenizer
  def tokens(text):
    encoded_input = tokenizer.encode(text, return_tensors='pt')
    decoded_input = tokenizer.convert_ids_to_tokens(encoded_input[0])
    decoded_input = [token.replace('Ġ', '').lower() for token in decoded_input]  # replace RoBERTa special token
    return decoded_input

  cols = [f'question_{lang}',
          f'disease_{lang}',
          f'drug_{lang}',
          f'treatment_{lang}',]
  for col in cols:
    data[col + '_tokens'] = data[col].apply(tokens)

  def biotag(row):
    qn_tokens = row[f'question_{lang}_tokens'][1:-1]
    dis_tokens = row[f'disease_{lang}_tokens'][1:-1]      # for disease, drug and treatment remove <s> and </s> tokens for proper matching (NOTE : for empty string, this gives empty list)
    drug_tokens = row[f'drug_{lang}_tokens'][1:-1]
    treat_tokens = row[f'treatment_{lang}_tokens'][1:-1]

    i = 0
    biotags = []
    while i < len(qn_tokens):
      token = qn_tokens[i]
      # if current token matches with the starting tokens of annotated disease, drug or treatment
      if ((len(dis_tokens) > 0 and (token in dis_tokens[0] or dis_tokens[0] in token)) or
         (len(drug_tokens) > 0 and (token in drug_tokens[0] or drug_tokens[0] in token)) or
         (len(treat_tokens) > 0 and (token in treat_tokens[0] or treat_tokens[0] in token))):

        entity = ""   # label for detected entity
        if len(dis_tokens) > 0 and (token in dis_tokens[0] or dis_tokens[0] in token):
          entity_tokens = dis_tokens
          entity = "disease"
        elif len(drug_tokens) > 0 and (token in drug_tokens[0] or drug_tokens[0] in token):
          entity_tokens = drug_tokens
          entity = "drug"
        elif len(treat_tokens) > 0 and (token in treat_tokens[0] or treat_tokens[0] in token):
          entity_tokens = treat_tokens
          entity = "treatment"

        # define matching function to compute similarity of entity and question subpart's tokens
        def match_tokens(ent_toks, qn_toks, thresh):
          cnt = 0
          match_toks = []   # store the set of question tokens which match with entity tokens
          for ent_tok in ent_toks:
            for qn_tok in qn_toks:
              if (ent_tok in qn_tok) or (qn_tok in ent_tok):
                cnt += 1
                match_toks.append(qn_tok)
                break

          match_toks = list(set(match_toks))
          return cnt/len(ent_toks), match_toks

        # if detected entity approximately matches with current substring based on threshold value
        thresh = 0.8
        # print(entity_tokens)
        # print(qn_tokens[i:min(i+len(entity_tokens), len(qn_tokens))])
        f_match, match_toks = match_tokens(entity_tokens, qn_tokens[i:min(i+len(entity_tokens), len(qn_tokens))], thresh)

        # print("Match ", f_match)
        # print("Match toks ", match_toks)
        if f_match >= thresh:
          idx = i   # store current value of idx
          # add B, I tags for all tokens matching with those of the detected entity
          while i < min(idx + len(entity_tokens), len(qn_tokens)):
            if qn_tokens[i] in match_toks:
              if i == idx:
                biotags.append(f'B-{entity}')
              else:
                biotags.append(f'I-{entity}')
            else:
              biotags.append('O')
            i += 1
          continue  # to prevent skipping an extra index
        else: # since entity thought to match doesn't actually match completely, it is not the start token of some entity. So, add O biotag to the current token only
          biotags.append('O')

      else:
        biotags.append('O')
      i+=1

    # The above approach might cause some intermediate tokens for any entity to be labelled O, even though its surrounding tokens are B/I tokens. We fix such tokens as postprocessing
    i = 0
    while i < len(biotags):
      biotag = biotags[i]
      if (i>0 and i<len(biotags)-1):
        prev_tag = biotags[i-1]
        next_tag = biotags[i+1]
        if (('B-' in prev_tag or 'I-' in prev_tag) and 'I-' in next_tag):
          entity = prev_tag[2:]
          biotags[i] = 'I-' + entity
      i+=1
    return biotags

  data[f'question_{lang}_biotags'] = data.apply(biotag, axis=1)
  return data

In [14]:
x = biotagging(train_.iloc[[18]], 'english')
print("Question : ", x.iloc[0][['question_english']].values[0])
print("Disease : ", x.iloc[0][['disease_english']].values[0])
print("Drug : ", x.iloc[0][['drug_english']].values[0])
print("Treatment : ", x.iloc[0][['treatment_english']].values[0])
print(x.iloc[0][['question_english_biotags']].values[0])

Question :  scoliosis. does it effect the stomach and breathing.
Disease :  Scoliosis
Drug :  
Treatment :  
['B-disease', 'I-disease', 'I-disease', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [15]:
train = biotagging(train_, 'english')
test = biotagging(test_, 'english')

In [16]:
from datasets import Dataset

tag2label = {
    'O': 0,
    'B-disease':1,
    'I-disease':2,
    'B-drug':3,
    'I-drug':4,
    'B-treatment':5,
    'I-treatment':6
}

def preprocess(data: pd.DataFrame, lang):
  sents = list(data[f'question_{lang}'])
  labels = list(data[f'question_{lang}_biotags'].apply(lambda x:[tag2label[tag] for tag in x]))

  dataset = Dataset.from_dict(
      {
          'sentence': sents,
          'labels': labels
      }
  )

  max_length = 512
  special_token_label = -100    # define label for special token
  def tokenize_function(examples):
    return tokenizer(examples['sentence'], padding='max_length', truncation=True, max_length=max_length)

  def align_labels(examples):
    labels = examples['labels']
    for sent_labels in labels:
      sent_labels.extend([special_token_label] * (max_length - len(sent_labels)))   # add special token labels at end
    return examples

  dataset = dataset.map(tokenize_function, batched=True)
  dataset = dataset.map(align_labels, batched=True)
  return dataset

tokenized_train = preprocess(train, 'english')
tokenized_test = preprocess(test, 'english')

Map:   0%|          | 0/720 [00:00<?, ? examples/s]

Map:   0%|          | 0/720 [00:00<?, ? examples/s]

Map:   0%|          | 0/241 [00:00<?, ? examples/s]

Map:   0%|          | 0/241 [00:00<?, ? examples/s]

In [17]:
tokenized_train['labels'][0]

[0,
 0,
 3,
 4,
 4,
 0,
 0,
 0,
 0,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100,
 -100

# Model Creation

In [18]:
from transformers import RobertaForTokenClassification

model_name = "roberta-base"
model = RobertaForTokenClassification.from_pretrained(model_name, num_labels = len(tag2label) + 1)

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [19]:
from transformers import DataCollatorForTokenClassification, Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="ner_model",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    evaluation_strategy="steps",
    eval_steps=500,
    num_train_epochs=10,
    load_best_model_at_end=True,
    learning_rate=5e-5,
    push_to_hub=False,
)

data_collator = DataCollatorForTokenClassification(tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test
)

In [ ]:
trainer.train()

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [ ]:
# Evaluate the model on the test dataset
results = trainer.evaluate()

# Print the evaluation results
print(results)

{'eval_loss': 0.013437559828162193, 'eval_runtime': 7.7029, 'eval_samples_per_second': 31.287, 'eval_steps_per_second': 7.919, 'epoch': 10.0}


In [ ]:
predictions = trainer.predict(tokenized_test)

In [ ]:
pred_vals = predictions.predictions

In [ ]:
pred_vals[0].shape

(512, 8)

In [ ]:
import numpy as np
predicted_labels = np.argmax(pred_vals, axis=2)
predicted_labels.shape

(241, 512)

In [ ]:
predicted_labels[3]

array([0, 0, 0, 3, 4, 0, 1, 4, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,

In [ ]:
tokenized_test['labels'][3]

[0,
 0,
 0,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,


In [ ]:
len(tokenized_test['labels'][0])

512

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

pred_labels = predicted_labels.flatten()
actual_labels = np.array(tokenized_test['labels']).flatten()

print(classification_report(actual_labels, pred_labels))
print(confusion_matrix(actual_labels, pred_labels))

              precision    recall  f1-score   support

           0       0.94      0.87      0.91      2511
           1       0.53      0.64      0.58       121
           2       0.46      0.69      0.56       181
           3       0.51      0.77      0.61        64
           4       0.51      0.70      0.59       166
           5       0.70      0.72      0.71        46
           6       0.63      0.41      0.50        95
           7       1.00      1.00      1.00    120208

    accuracy                           1.00    123392
   macro avg       0.66      0.72      0.68    123392
weighted avg       1.00      1.00      1.00    123392

[[  2191     41    110     35     93     12     18     11]
 [    32     77      6      3      1      1      0      1]
 [    31     14    125      1      7      0      3      0]
 [    10      1      0     49      3      1      0      0]
 [    37      3      2      5    117      0      2      0]
 [     4      6      0      3      0     33      0    

In [ ]:
tag2label

{'O': 0,
 'B-disease': 1,
 'I-disease': 2,
 'B-drug': 3,
 'I-drug': 4,
 'B-treatment': 5,
 'I-treatment': 6}